### PR TITLE
Fixed unnecessarily stopping ALL keydown events

### PR DESCRIPTION
**Pull request by Anoesj**
The keydown event listener `handleKeydown` very aggressively stops propagation of all keydown events in every scenario (even if `use-keyboard` is `false`). This is blocking typing, browser shortcuts, **anything that involves keyboard input**!

I moved `preventDefault` and commented `stopPropagation`, since I don't see any reason to use `stopPropagation`. It's probably not perfect, but maybe the keyboard functionality should be reviewed and rewritten altogether, because I don't really see why you'd need it on the document element. If the idea was to support keyboard navigation, why not make the range sliders focusable and listen to events on the range sliders itself, instead of on the document element?

### CODE REVIEW

**Review by kvn29 — APPROVED** [review]

**Review by marc-tech — APPROVED** [review]
NICE

**Review by kevinfavv — APPROVED** [review]

**Comment by kevinfavv** [comment]
Nice changes !

**Review by gmerwan — APPROVED** [review]

**Review by gmerwan — APPROVED** [review]

**Comment by Anoesj** [comment]
@xwpongithub Hello?

**Comment by alfonsozunigaj** [comment]
Thanks dude! You saved me!

**Comment by thdung002** [comment]
You saved me bro.... take a day to find what make this library do that... fck

**Comment by lukasborawski** [comment]
@xwpongithub The fix from @Anoesj works super fine. Can you merge it? It's not good to keep dependencies from other users PR's :) @Anoesj thanks man, please do not remove your fork 😃. And for others, for now: 
```
"vue-range-component": "Anoesj/vue-range-slider#master",
```
add this to your `package.json` file.

**Review by lukasborawski — APPROVED** [review]

**Review by xunita — APPROVED** [review]

**Comment by winstonfale** [comment]
> @xwpongithub The fix from @Anoesj works super fine. Can you merge it? It's not good to keep dependencies from other users PR's :) @Anoesj thanks man, please do not remove your fork 😃. And for others, for now:
> 
> ```
> "vue-range-component": "Anoesj/vue-range-slider#master",
> ```
> 
> add this to your `package.json` file.

thank you so much sir. u save me

**Comment by Anoesj** [comment]
Thank you for merging @xwpongithub! Note that these are basically quickfixes, a more permanent solution might be better. IMO you should only add event listeners to `document` if you *really* need to, and if you do, you should probably only run `event.preventDefault()` and/or `event.stopPropagation()` if the event target is the range slider or one of its children, i.e.:
```javascript
document.addEventListener('touchmove', (event) => {
  if (this.$refs.sliderElement.contains(event.target)) {
    event.preventDefault();
    // do the slider things
  }
}, { passive: false, capture: false });
```

**Comment by xsanja** [comment]
Great ! Thank you  👍 🥇

**Comment by Javid-Izadfar** [comment]
@xwpongithub it's been months since this PR got merged, but no publish on NPM! this fix is a real lifesaver, to be honest

**Comment by daveycakes** [comment]
This is a really good fix, it would have saved me an hour today, and had me not looking like a goose in front of my client yesterday. Merge please.

**Pull request merged**
